name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Juice Shop
        run: |
          docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Retrying in 5s..."
            sleep 5
          done

      - name: Create ZAP workspace
        run: |
          mkdir -p zap-workspace
          chmod 777 zap-workspace

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network host \
            -v "$(pwd)":/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:3000 \
            -r zap-report.html || true
            
      - name: Prepare directory for reports
        run: |
          mkdir -p zap-reports
          mv zap-workspace/*.html zap-workspace/*.json zap-workspace/*.md zap-reports/ 2>/dev/null || true
          cp *.html *.json *.md zap-reports/ 2>/dev/null || true
          echo "Final reports:"
          ls -la zap-reports/

      - name: Verify if reports exist
        run: |
          if [ ! -f zap-reports/report_html.html ] && [ ! -f zap-reports/report_json.json ]; then
            echo "No reports found in zap-reports/, checking workspace..."
            ls -la zap-workspace/
            # Try to find reports anywhere
            find . -name "*.html" -o -name "*.json" -o -name "*.md" | head -10
          else
            echo "Reports found successfully!"
          fi

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-reports
          path: |
            zap-reports/
            zap-workspace/
         
